{% set name = "snakebite" %}
{% set version = "2.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 085238b4944cb9c658ee62d5794de936ac3d0c337c504b2cc86424a205ae978a

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed -vv .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - protobuf >2.4.1
    - argparse  # [py26]

test:
  imports:
    - snakebite
    - snakebite.protobuf

about:
  home: http://github.com/spotify/snakebite
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Pure Python HDFS client'

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
