travis:
  secure:
    BINSTAR_TOKEN: UDC1cmrO+BCiUmFChCIelWeDBA8yyKQHkDDUARRAc1ZN+gXJ44Hgd99C/H31tm7/CIfYtfmYCLKmfX4IyX7rl517fDqzVQtYYmfXkil7CcBld6UFn6OE4Q23AryOG4LdGNI9FFqKr3SjjcgVPSdZ4Ka00uOzStM/JI2myLBd8jvqM97dFk/6Yl1Px20ZMgOKrWP1hYt/33xYE3rzlqxVelf3sRV56UG2QovjpS+uXkSF78seI+es2DBm1ffFV2bkb/LoU6vEj8mH8saCFVJS1jyKCKsStJZuula2G0n8pfZ+hvp/335J+LH2rKkEUmNxbLVV4EuElaiKzLmAEjEDI5E/+/0rH6jddDphq9+r5H7LdJHsSrDINlJWQYWtCSBa/BAAQ0z7mh8+BolQqHyR74jZE+GnnHZ2VeOkFpBEVhTLIE9HQvQhofgQ3w6GeGK972Pjetm4xIikViIEbNToii4rXDZ+aAZ/dQ8o/CW0NyyeITBMBow9MqdP6CWExgmvQYgcr6E3Re5IhQrROb7JREYWot8lOEF7L3ZhzHiA7OUeTkuV7rq4e+w5dMhsKNjYAz/6ZEhoLdvt24TBRzAxWF9TQh5661/cz7eg0cev/j5bfq/P2ajjIZgJPMgt7QqV6wMY4sMQ39+i8Hkt5Ay6thUFWHzw0fWZgGwnx5ysCP4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
